openapi: 3.0.0
info:
  title: Rich Content API
  version: 1.0.0
  description: API for rich content blocks, embedded content, and contact forms

paths:
  /api/content/blocks:
    get:
      summary: Get all rich content blocks for a profile
      parameters:
        - name: profileId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of rich content blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RichContentBlock'

    post:
      summary: Create a new rich content block
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRichContentBlock'
      responses:
        '201':
          description: Rich content block created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichContentBlock'

  /api/content/blocks/{id}:
    get:
      summary: Get a specific rich content block
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rich content block details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichContentBlock'

    put:
      summary: Update a rich content block
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRichContentBlock'
      responses:
        '200':
          description: Rich content block updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichContentBlock'

    delete:
      summary: Delete a rich content block
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rich content block deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: boolean

  /api/content/css:
    get:
      summary: Get custom CSS for a profile
      parameters:
        - name: profileId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Custom CSS for the profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  cssCode: string
                  isLive: boolean

    post:
      summary: Create or update custom CSS for a profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomCSS'
      responses:
        '200':
          description: Custom CSS updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomCSS'

  /api/content/form/submit:
    post:
      summary: Submit a contact form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactSubmission'
      responses:
        '200':
          description: Contact form submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: boolean
                  submissionId: string

components:
  schemas:
    RichContentBlock:
      type: object
      properties:
        id:
          type: string
        profileId:
          type: string
        contentType:
          type: string
          enum: [embed, text, form, gallery]
        content:
          type: string
        title:
          type: string
          nullable: true
        position:
          type: integer
        isVisible:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateRichContentBlock:
      type: object
      properties:
        profileId:
          type: string
        contentType:
          type: string
          enum: [embed, text, form, gallery]
        content:
          type: string
        title:
          type: string
          nullable: true
        position:
          type: integer
        isVisible:
          type: boolean
      required:
        - profileId
        - contentType
        - content
        - position

    UpdateRichContentBlock:
      type: object
      properties:
        contentType:
          type: string
          enum: [embed, text, form, gallery]
        content:
          type: string
        title:
          type: string
          nullable: true
        position:
          type: integer
        isVisible:
          type: boolean

    CustomCSS:
      type: object
      properties:
        id:
          type: string
        profileId:
          type: string
        cssCode:
          type: string
        isLive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ContactSubmission:
      type: object
      properties:
        profileId:
          type: string
        formId:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        email:
          type: string
          format: email
          nullable: true
        message:
          type: string
          nullable: true
      required:
        - profileId